### ISSUE TITLE
Switch ETEngine to use solely AD-files

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etengine#576]
### Following Objects:
- [x] Carriers
- [x] Gqueries
- [x] Inputs
- [x] Presets ( quintel/etengine#579 )
- [x] Nodes ( **see below!** )
- [x] Edges
- [x] Dataset (area properties)
- [x] The whole 'production graph' that has been calculated by Refinery
### For Node:
- [x] basic loading of all the nodes in ETEngine for the graph
- [x] converter_costs ( quintel/etsource#434 )
- [x] employment ( quintel/etsource#438 )
- [x] Node groups (quintel/etsource#430 )
- [x] network characteristics ? ( quintel/etsource#433 )

For all these parts except the 'production-mode graph': import script needs to be adapted as well
